# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from src.grpc_service import hello_pb2 as hello__pb2


class HelloStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.hello_action = channel.unary_unary(
            '/sample.Hello/hello_action',
            request_serializer=hello__pb2.HelloRequest.SerializeToString,
            response_deserializer=hello__pb2.HelloResponse.FromString,
        )


class HelloServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def hello_action(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'hello_action': grpc.unary_unary_rpc_method_handler(
            servicer.hello_action,
            request_deserializer=hello__pb2.HelloRequest.FromString,
            response_serializer=hello__pb2.HelloResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'sample.Hello', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
